### ISSUE TITLE
Collect a map of data about each fetch operation

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/ontofetch#1]
As the tool does its job, we need to collect a map of information. We'll be adding to this map, but as a first pass it should include: directory name, requested IRI.

**Comment by rctauber** [comment]
The map now looks like this:

```
{"eco"
    {:request-url "http://purl.obolibrary.org/obo/eco.owl",
     :location "foo2/eco.owl",
     :redirect-path ["http://purl.obolibrary.org/obo/eco.owl" "https://raw.githubusercontent.com/evidenceontology/evidenceontology/master/eco.owl"], 
     :metadata {:ontology-iri "http://purl.obolibrary.org/obo/eco.owl",
                :version-iri "http://purl.obolibrary.org/obo/eco/releases/2017-09-21/eco.owl"}}}
```

Any other details we need to include? Going to add imports to the metadata as well.

**Comment by jamesaoverton** [comment]
Good. Let's include the directory name inside the map, then close this issue. We'll make revisions as we go.

**Comment by rctauber** [comment]
Should I just change `:location` to `:directory`? (and return foo2 instead of foo2/eco.owl)

**Comment by jamesaoverton** [comment]
Let's include both location and directory.
