### ISSUE TITLE
Implement function to extract owl:Ontology XML element

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/ontofetch#10]
Given a fetched ontology, we should be able to extract all the metadata. We only need to do this for the main ontology, not its imports. The output XML should include:

1. the XML declaration
2. the DOCTYPE declaration, if present
3.  the `rdf:RDF` root element, with namespace declarations and just one child:
4. the `owl:Ontology` element, with all its content

**Comment by rctauber** [comment]
Should be working for XML & Jena methods, but I need to write tests for them. Still need to create a parsing method for OWLAPI.
