### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/ontofetch#11]
As we start adding more functionality, tests will help us be confident that we haven’t broken existing functionality.

A unit test is helpful for testing a single complex function, but the emphasis should be on integration tests of the “happy path” from valid input to valid output. This will require adding some sample input and output to the repository. Examples should be as small as possible to test the target feature.

**Comment by rctauber** [comment]
One test added in d0c0138
I'll be adding more but this is at least a start

**Comment by rctauber** [comment]
Current test coverage
```
|----------------------+---------+---------|
|            Namespace | % Forms | % Lines |
|----------------------+---------+---------|
|       ontofetch.core |    7.47 |   17.14 |
|      ontofetch.files |   56.47 |   63.89 |
|       ontofetch.html |   99.47 |  100.00 |
|       ontofetch.http |   82.25 |   80.56 |
| ontofetch.parse.jena |   68.62 |   68.25 |
|  ontofetch.parse.owl |  100.00 |  100.00 |
|  ontofetch.parse.xml |  100.00 |  100.00 |
|      ontofetch.utils |   54.00 |   57.14 |
|----------------------+---------+---------|
|            ALL FILES |   64.27 |   67.09 |
|----------------------+---------+---------|
```
