### ISSUE TITLE
Measure and report how long each fetch operation takes

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/ontofetch#15]
This could help track down problems. The simplest implementation would be to add a start timestamp and an end timestamp to the record.

**Comment by rctauber** [comment]
While we're updating this in the catalog anyway, I'd like to add an 'error' field.
Do we want to consider a data structure something like below for implementation of #21 & #22? Single fetch requests would only have one entry in the content vector.

```
[{:timestamp "YYYY-MM-DD HH:MM",
  :content
  [{:request-url "url",
    :directory "dir",
    :location "dir/file.owl",
    :redirect-path
    [...],
    :process-time "x ms",          (other names could be: response-time, time?)
    :error-log "hopefully nil",
    :metadata
    {:ontology-iri "iri",
     :version-iri "iri",
     :imports {...}}}
    {next request...}]}

 {:timestamp "YYYY-MM-DD HH:MM",
  :content
  [{mapped request 1}
   {mapped request 2}
   ...]}
 ...]
```

**Comment by jamesaoverton** [comment]
An error field is a good idea. For each fetch, how about: start-time, end-time, duration? For the whole catalog, how about: last-updated?  I think we should track seconds (we don't need more precision than that).

**Comment by rctauber** [comment]
"last updated" can go into #16 as well. Do we want to keep old logs? Or replace entries for each ontology? For example, each time we fetch OBI, the entry for OBI gets updated...

**Comment by jamesaoverton** [comment]
We want to keep everything, forever. If OBI hasn't update, then we just keep a record saying that we checked and it wasn't modified.

So yes, we should think about breaking the catalog into pieces or using some sort of local database. That can go in its own issue, and it can wait a little while.
