### ISSUE TITLE
Record HTTP Etag and Last-Modified headers

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/ontofetch#16]
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified

When fetching an artifact using HTTP, we should look for these response headers. If present, add them to the catalog record.

Later we can use them to check whether an artifact has been modified and avoid downloading it again.

**Comment by rctauber** [comment]
Should we still download the imports if it hasn't been updated?

**Comment by jamesaoverton** [comment]
Good questions.

We can also check imports to see if they’ve been modified. If any import has been modified (or we’re not sure) then the ontology is (or could be) different.

If we have a catalog record but no files, then I think we should fetch the files.

Whatever we do, we need to communicate it clearly to the user.

**Comment by rctauber** [comment]
Re missing files:
Should we just assume that the files are in the same place that they were downloaded to, with the same name? (based on the user's request)

Re imports:
Would we need to catalog the etag/last-modified dates on the imports as well? The imports entry could be structured as so:
```
:imports 
[{:url ""
  :indirect-imports []  *
  :etag "" 
  :last-modified ""}
  {next import} ... ]
```
\* I was thinking this could just be a list, and we'd refetch the indirs every time, but it could just be another vector of maps with the same data as the imports vector...

**Comment by jamesaoverton** [comment]
I was confused about this, but I think that #24 makes it more clear: fetch should always fetch. When we have a project, which may have multiple versions, then we may want to compare before fetching. In that case we'll look stuff up in the catalog for comparison.

Missing files adds more complexity. I'm not sure what to do. We might want another operation to clean up the catalog. If we have a catalog entry but the directory is gone, maybe we delete the catalog entry. If we have a catalog entry and the directory exists but some files are missing, then I'm not sure what to do. This probably deserves its own issue. It doesn't seem urgent to me.

**Comment by rctauber** [comment]
Okay, cool. I added in checks for the existing file and it's all part of the same process right now, but I'll divide it up for #24.
