### ISSUE TITLE
Store a catalog of operation results

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/ontofetch#2]
Building on #1, we should create an EDN file that contains a vector with a map for each operation performed. This will let us report a list of the fetched ontologies.

See the fist few forms of https://github.com/knocean/knode/blob/master/src/knode/upstream.clj for a nice implementation.

**Comment by rctauber** [comment]
Commit be3af03 added catalog.edn (does not have artifact records for #7 yet)

**Comment by rctauber** [comment]
Commit 8c46383 changed to vector of requests
