### ISSUE TITLE
Implement `-w` `--working-dir` option

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/ontofetch#25]
The working directory is the root directory for the catalog, the configuration file, and where directories for artifacts are created -- everything that ontofetch read and writes. It defaults to `.` (the current directory), which is the current behaviour. The working directory must exist. We will not create it. If it doesn't exist, we throw an exception complaining that "working directory X does not exist".

**Comment by rctauber** [comment]
Where should the `ont-element.owl` file be stored? Currently, it just goes in `.` (would be the working-dir in this case), but I'm wondering if we should create a folder (e.g. `./elements` or `./extracts`) within the working-dir to hold the element files? They could also go in the dir for the fetch, but with the obo-metadata project, I found it easier to have them outside of that (especially when zipping).

**Comment by jamesaoverton** [comment]
`extract` should probably require an output dir.

**Comment by rctauber** [comment]
Okay. I'll leave it as-is for now, and change it when I add the `extract` command. I'm going to commit this change, then my next task is #24.
