### ISSUE TITLE
Compress files on disk

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/ontofetch#3]
Since OWL XML files are verbose, we should compress them on disk. See `spit-gzipped!` and `slurp-gzipped!` in https://github.com/knocean/knode/blob/master/src/knode/upstream.clj

**Comment by rctauber** [comment]
Do we want to keep the full dir & the zipped dir, or delete the full dir when we're done compressing?

**Comment by jamesaoverton** [comment]
Good question. I'm not sure. What do you think?

**Comment by rctauber** [comment]
I think it would make sense to delete the full dir, otherwise why compress it at all? Especially if we wanted to run this over a list of IRIs to fetch.
