### ISSUE TITLE
Command records and artifact records

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/ontofetch#7]
Building on #1, before we get to #2 ...

In our catalog we'll want a vector with one element for each time the user asked us to fetch something -- let's call that a "command record". The command record should store the directory and IRI that the user provided, and maybe the date and whether we succeeded, and any error messages. For each command record we'll also want a vector with entries for each artifact that we fetched -- call that an "artifact record". The artifact record should contain the information from #1.

**Comment by rctauber** [comment]
Commit be3af03 added date to map

**Comment by rctauber** [comment]
Implemented by commit d56e582
